### ISSUE TITLE
What is the source?

### ISSUE THREAD

**Issue by ahangarha** [openafg/afghanistan-provinces-districts-villages#1]
These data are collected from what source?

**Comment by colincookman** [comment]
Hi - I'd also like to know the source for this data (particularly villages) - thank you!

**Comment by matiullah-netlinks** [comment]
1- Data for the provinces is collected manually from Google Maps.
2- Data for the districts is collected from [World Bank Data](https://www.worldbank.org/en/data/interactive/2019/08/01/afghanistan-district-level-visualization).
3- The source for the villages is unknown.

**Comment by matiullah-karimi** [comment]
1- Data for the provinces is collected manually from Google Maps.
2- Data for the districts is collected from [World Bank Data](https://www.worldbank.org/en/data/interactive/2019/08/01/afghanistan-district-level-visualization).
3- The source for the villages is unknown.
